pipelines:
  default:
    - step:
        name: Bitbucket GitHub Sync
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --mirror https://x-token-auth:$BITBUCKET_VARIABLE@bitbucket.org/solavisetech_internship/bitbucket-github_sync.git
          - cd bitbucket-github_sync.git
          - git push --mirror https://x-token-auth:$GITHUB_VARIABLE@github.com/Chiekadarrell/bitbucket-github_sync.git
